spring:
  application:
    name: schedule
  config:
    import:
      - optional:file:.env[.properties]
  profiles:
    active: local

mybatis:
  mapper-locations: /mybatis/mappers/*.xml
  type-aliases-package: com.schedule


---
spring:
  sql:
    init:
      mode: always
  config:
    activate:
      on-profile: local
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: ${LOCAL_DATA_BASE_URL}
    username: ${LOCAL_DATA_BASE_USERNAME:sa}
    password: ${LOCAL_DATA_BASE_PASSWORD:}
  flyway:
    user: ${LOCAL_DATA_BASE_USERNAME:sa}
    password: ${LOCAL_DATA_BASE_PASSWORD:}
    clean-disabled: true
    locations: classpath:db/migration
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=POSTGRESQL;DATABASE_TO_LOWER=TRUE;CASE_INSENSITIVE_IDENTIFIERS=TRUE
  h2:
    console:
      enabled: true
server:
  port: ${LOCAL_HOST:8080}

secret:
  aes-key: ${LOCAL_SECRET_KEY:my-secret-keyek-terces-ym}
