
CREATE
    SEQUENCE MEMBER_ID_SEQ
    START
        WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE
        1;

CREATE TABLE member
(
    MEMBER_ID           BIGINT                DEFAULT NEXTVAL('MEMBER_ID_SEQ') PRIMARY KEY,
    MEMBER_LOGIN_ID     VARCHAR(50)  NOT NULL UNIQUE,
    ENCRYPT_TYPE        VARCHAR(20)  NOT NULL,
    PASSWORD            VARCHAR(200) NOT NULL,
    LOCK_COUNT          INT                   DEFAULT 0,
    FIRST_NAME          VARCHAR(6)   NOT NULL,
    LAST_NAME           VARCHAR(6)   NOT NULL,
    HOME_DORO_YN        VARCHAR(1)   NOT NULL DEFAULT 'Y',
    HOME_JI_BUN_YN      VARCHAR(1)   NOT NULL DEFAULT 'N',
    HOME_ZIP_NO         VARCHAR(50),
    HOME_ADDRESS        VARCHAR(50),
    HOME_ADDRESS_DETAIL VARCHAR(50),
    CELL_FIRST_NUMBER   VARCHAR(10),
    CELL_MIDDLE_NUMBER  VARCHAR(10),
    CELL_LAST_NUMBER    VARCHAR(10),
    CREATE_ID           BIGINT,
    CREATE_DATE         TIMESTAMP             DEFAULT CURRENT_TIMESTAMP,
    MODIFY_ID           BIGINT,
    MODIFY_DATE         TIMESTAMP             DEFAULT CURRENT_TIMESTAMP
);

/**/

CREATE TABLE MEMBER_DETAIL
(
    MEMBER_ID          BIGINT PRIMARY KEY,
    GENDER             VARCHAR(1),
    DATE_OF_BIRTH      DATE,
    OCCUPATION         VARCHAR(50),
    COMPANY_NAME       VARCHAR(100),
    PROFILE_IMAGE_PATH VARCHAR(200),
    SOCIAL_MEDIA_LINK  VARCHAR(200),
    MEMBER_BIO         TEXT,
    CREATE_ID          BIGINT,
    CREATE_DATE        TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    MODIFY_ID          BIGINT,
    MODIFY_DATE        TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE MEMBER_DETAIL
    ADD CONSTRAINT FK_MEMBER_DETAIL_MEMBER
        FOREIGN KEY (MEMBER_ID)
            REFERENCES MEMBER (MEMBER_ID);

/**/

CREATE
    SEQUENCE TECH_STACK_CATEGORY_SEQ
    START
        WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE
        1;

CREATE TABLE TECH_STACK_CATEGORY
(
    TECH_STACK_CATEGORY_ID   BIGINT    DEFAULT NEXTVAL('TECH_STACK_CATEGORY_SEQ') PRIMARY KEY,
    TECH_STACK_CATEGORY_NAME BIGINT NOT NULL,
    CREATE_ID                BIGINT,
    CREATE_DATE              TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    MODIFY_ID                BIGINT,
    MODIFY_DATE              TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

/**/

CREATE
    SEQUENCE TECH_STACK_SEQ
    START
        WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE
        1;

CREATE TABLE TECH_STACK
(
    TECH_STACK_ID          BIGINT    DEFAULT NEXTVAL('TECH_STACK_SEQ') PRIMARY KEY,
    TECH_STACK_CATEGORY_ID BIGINT      NOT NULL,
    TECH_STACK_NAME        VARCHAR(50) NOT NULL UNIQUE,
    CREATE_ID              BIGINT,
    CREATE_DATE            TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    MODIFY_ID              BIGINT,
    MODIFY_DATE            TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE TECH_STACK
    ADD CONSTRAINT FK_TECH_STACK_CATEGORY_TECH_STACK
        FOREIGN KEY (TECH_STACK_CATEGORY_ID)
            REFERENCES TECH_STACK_CATEGORY (TECH_STACK_CATEGORY_ID);

